ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- 새로운 사용자 계정 생성 (sys 계정으로 진행)
CREATE USER library_sys IDENTIFIED BY library_sys;

-- 사용자 계정 권한 부여 설정
GRANT RESOURCE, CONNECT TO library_sys;

-- 객체가 생성될 수 있는 공간 할당량 지정
ALTER USER library_sys DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

------------------------------------------------------
DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_MEM_NO;

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL PRIMARY KEY,
	"MEMBER_NAME" VARCHAR(20) NOT NULL,
	"MEMBER_ID"	VARCHAR2(50)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(100)		NOT NULL,
	"LATE_FEE" NUMBER DEFAULT 0,
	"ISLIBRARIAN" VARCHAR2(10) DEFAULT 'N' NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '회원 이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."LATE_FEE" IS '연체료';

COMMENT ON COLUMN "MEMBER"."ISLIBRARIAN" IS '사서 여부';

CREATE SEQUENCE SEQ_MEM_NO NOCACHE;
----------------------------------------------------------
DROP TABLE "BOOK" CASCADE CONSTRAINTS;
DROP TABLE RENTED_BOOK CASCADE CONSTRAINTS;


CREATE TABLE "BOOK" (
	"BOOK_NO" VARCHAR2(30) NOT NULL PRIMARY KEY,
	"BOOK_NAME" VARCHAR2(500) NOT NULL,
	"AUTHOR" VARCHAR2(300) NOT NULL,
	"PUBLISHER" VARCHAR2(200) NOT NULL
);


COMMENT ON COLUMN "BOOK"."BOOK_NO" IS '도서 번호';
COMMENT ON COLUMN "BOOK"."BOOK_NAME" IS '도서 제목';
COMMENT ON COLUMN "BOOK"."AUTHOR" IS '작가';
COMMENT ON COLUMN "BOOK"."PUBLISHER" IS '출판사';

-----------------------------------------------------------------
DROP TABLE RENTED_BOOK CASCADE CONSTRAINTS;
CREATE TABLE "RENTED_BOOK"(
	"BOOK_NO" VARCHAR2(30) NOT NULL PRIMARY KEY REFERENCES "BOOK"("BOOK_NO"),
	"RENT_DATE" DATE DEFAULT SYSDATE NOT NULL,
	"RENT_MEMBER_NO" NUMBER NOT NULL REFERENCES "MEMBER"("MEMBER_NO")	
);


COMMENT ON COLUMN "RENTED_BOOK"."BOOK_NO" IS '도서 번호';
COMMENT ON COLUMN "RENTED_BOOK"."RENT_DATE" IS '대출 일자';
COMMENT ON COLUMN "RENTED_BOOK"."RENT_MEMBER_NO" IS '대여자 회원 번호';

COMMIT;

-------------------------------------------------------------

INSERT INTO "MEMBER" VALUES(SEQ_MEM_NO.NEXTVAL, '이정하', '1111', '1111', DEFAULT, DEFAULT);
INSERT INTO "MEMBER" VALUES(SEQ_MEM_NO.NEXTVAL, '김제니', '2222', '2222', DEFAULT, DEFAULT);
INSERT INTO "MEMBER" VALUES(SEQ_MEM_NO.NEXTVAL, '양세찬', '3333', '3333', DEFAULT, DEFAULT);
INSERT INTO "MEMBER" VALUES(SEQ_MEM_NO.NEXTVAL, '유재석', '4444', '4444', DEFAULT, 'Y');

COMMIT;

--------------------------------------------------------------
INSERT INTO "BOOK" VALUES('740.77', '해커스 토익 기출 VOCA', 'David Cho', '해커스어학연구소');
INSERT INTO "BOOK" VALUES('325.211', '세이노의 가르침', '세이노(SayNo)', '데이원');
INSERT INTO "BOOK" VALUES('325.08', '데일 카네기 인간관계론(무삭제 완전판)', 'Dale Carnegie', '현대 지성');
INSERT INTO "BOOK" VALUES('470.4', '물고기는 존재하지 않는다', 'Lulu Miller', '곰출판');
INSERT INTO "BOOK" VALUES(' L 813.7-ㄱ989ㅂ', '불편한 편의점', '김호연', '나무옆의자');
INSERT INTO "BOOK" VALUES(' 332.6-ㄱ939ㅅ=c.8', '선량한 차별주의자', '김지혜', '창비');
INSERT INTO "BOOK" VALUES('Y 808-ㅎ147ㅎ-v.52', '열하일기', '박지원', '하서출판사');
INSERT INTO "BOOK" VALUES('J 813.508-ㅈ224ㅊ-v.4', '박씨부인전', '김종광', '창비');

COMMIT;


-----------------------------------------------------------------------------------


SELECT MEMBER_NO, MEMBER_NAME , MEMBER_ID,LATE_FEE, ISLIBRARIAN 
FROM "MEMBER"
WHERE MEMBER_ID = '1111'
AND MEMBER_PW ='1111';

UPDATE "MEMBER" SET LATE_FEE =1000
WHERE MEMBER_NO =1;
COMMIT;



SELECT BOOK_NO , BOOK_NAME , AUTHOR , PUBLISHER , NVL(TO_CHAR(RENT_MEMBER_NO),'-') AS RENT_MEMBER_NO, NVL(TO_CHAR(RENT_DATE,'YYYY"년" MM"월" DD"일"'),'-')AS RENT_DATE
FROM BOOK b 
LEFT JOIN RENTED_BOOK USING(BOOK_NO);

SELECT * FROM RENTED_BOOK rb ;
SELECT * FROM "MEMBER" m ;
INSERT INTO RENTED_BOOK rb VALUES('740.77',DEFAULT, 1);



 ROLLBACK;
DELETE FROM "BOOK"
WHERE BOOK_NO = 'J 813.508-ㅈ224ㅊ-v.4';

COMMIT;


SELECT BOOK_NO , BOOK_NAME , AUTHOR , PUBLISHER
FROM "BOOK" b 
WHERE BOOK_NO = ' 332.6-ㄱ939ㅅ=c.8';

UPDATE BOOK SET  BOOK_NAME ='', AUTHOR ='', PUBLISHER =''
WHERE BOOK_NO =






